---
# tasks file for hashicorp vaultd deployment
# all tasks are in a block just so we can set the ansible_connection to local

- name: Write certificate to Hashicorp Vault
  vars:
    ansible_connection: local
  block:
    - name: More testing
      when:
        - certmgmt_provision_return_object is defined
        - certmgmt_provision_return_object | length > 0
      ansible.builtin.debug:
        msg:
          - '{{ certmgmt_provision_return_object | community.general.json_query(json_query) }}'
      vars:
        json_query: "[?certmgmt_common_name=='{{ item.certmgmt_common_name }}']"

    - name: Write certificates to Vault
      community.hashi_vault.vault_write:
        path: '{{ item.certmgmt_vault_path }}'
        data:
          private_key: '{{ certmgmt_provision_return_object | community.general.json_query(key_query) }}'
          certificate: '{{ certmgmt_provision_return_object | community.general.json_query(certificate_query) }}'
          chain: '{{ certmgmt_provision_return_object | community.general.json_query(chain_query) }}'
          common_name: '{{ item.certmgmt_common_name }}'
      vars:
        key_query: "[?certmgmt_common_name=='{{ item.certmgmt_common_name }}'].certmgmt_private_key | [0]"
        chain_query: "[?certmgmt_common_name=='{{ item.certmgmt_common_name }}'].certmgmt_chain | [0]"
        certificate_query: "[?certmgmt_common_name=='{{ item.certmgmt_common_name }}'].certmgmt_cert | [0]"
