---
# tasks file for hashicorp vaultd deployment
# all tasks are in a block just so we can set the ansible_connection to local

- name: Write certificate to Hashicorp Vault
  vars:
    ansible_connection: local
  block:
    - name: Get first certificate when no common name is defined
      when:
        - certmgmt_provision_return_object is defined
        - certmgmt_provision_return_object | length > 0
        - item.certmgmt_common_name is not defined
      ansible.builtin.set_fact:
        certmgmt_this_cert: '{{ certmgmt_provision_return_object | first }}'
        certmgmt_this_vault_path: '{{ certmgmt_vault_path }}'

    - name: Get certificate by common name
      when:
        - certmgmt_provision_return_object is defined
        - certmgmt_provision_return_object | length > 0
        - item.certmgmt_common_name is defined
      ansible.builtin.set_fact:
        certmgmt_this_cert: '{{ certmgmt_provision_return_object | community.general.json_query(json_query) | first }}'
        certmgmt_this_vault_path: '{{ item.certmgmt_vault_path }}'
      vars:
        json_query: "[?common_name=='{{ item.certmgmt_common_name }}']"

    - name: Write certificates to Vault
      community.hashi_vault.vault_write:
        path: '{{ certmgmt_this_vault_path }}'
        data: '{{ certmgmt_this_cert }}'
