---
# tasks file for acme certs
# all tasks are in a block just so we can set the ansible_connection to local
# some of the openssl modules require outputting to a file
# all files are deleted by the last task

- name: '{{ this_certificate.certmgmt_common_name }}: Generate private key'
  community.crypto.openssl_privatekey_pipe:
    cipher: auto
    type: '{{ this_certificate.certmgmt_private_key_type | default(omit) }}'
    size: '{{ this_certificate.certmgmt_private_key_size | default(omit) }}'
    curve: '{{ this_certificate.certmgmt_private_key_curve | default(omit) }}'
  register: certmgmt_private_key

- name: '{{ this_certificate.certmgmt_common_name }}: Generate CSR'
  community.crypto.openssl_csr_pipe:
    privatekey_content: '{{ certmgmt_private_key.privatekey }}'
    common_name: '{{ this_certificate.certmgmt_common_name }}'
    subject_alt_name: '{{ this_certificate.certmgmt_subject_alt_name | default(omit) }}'
  register: certmgmt_csr

- name: '{{ this_certificate.certmgmt_common_name }}: Submit order to ACME directory'
  community.crypto.acme_certificate:
    account_key_content: '{{ certmgmt_acme_account_key }}'
    account_email: '{{ certmgmt_acme_email }}'
    account_uri: '{{ certmgmt_acme_account_uri | default(omit) }}'
    csr_content: '{{ certmgmt_csr.csr }}'
    dest: '{{ certmgmt_cert_dest_path }}'
    challenge: '{{ certmgmt_acme_challenge_type }}'
    acme_directory: '{{ certmgmt_acme_directory }}'
    remaining_days: '{{ certmgmt_acme_remaining_days | default(omit) }}'
    force: '{{ certmgmt_acme_force | default(omit) }}'
    acme_version: 2
    terms_agreed: true
    request_timeout: '{{ certmgmt_acme_request_timeout }}'
  register: certmgmt_acme_challenge

################################### Challenge Handling ###################################

- name: '{{ this_certificate.certmgmt_common_name }}: Import approriate challengbe task'
  ansible.builtin.include_tasks:
    file: 'acme_challenge_{{ certmgmt_acme_challenge_type }}.yml'
  vars:
    certmgmt_common_name: '{{ this_certificate.certmgmt_common_name }}'

################################# End Challenge Handling #################################

- name: '{{ this_certificate.certmgmt_common_name }}: Get information on generated certificate'
  community.crypto.x509_certificate_info:
    content: '{{ certmgmt_acme_result.all_chains[0].cert }}'
  register: certmgmt_info
  delegate_to: localhost

- name: '{{ this_certificate.certmgmt_common_name }}: Load cert info into variables'
  ansible.builtin.set_fact:
    certmgmt_provision_return_object: '{{ certmgmt_provision_return_object | default([]) + [certmgmt_this_cert] }}'
  vars:
    certmgmt_this_cert:
      chain: '{{ certmgmt_acme_result.all_chains[0].chain }}'
      cert: '{{ certmgmt_acme_result.all_chains[0].cert }}'
      private_key: '{{ certmgmt_private_key.privatekey }}'
      info: '{{ certmgmt_info }}'
      common_name: '{{ this_certificate.certmgmt_common_name }}'
      not_before: '{{ certmgmt_info.not_before }}'
      not_after: '{{ certmgmt_info.not_after }}'
      subject_alt_name: '{{ certmgmt_info.subject_alt_name }}'
  delegate_to: localhost
