---
# tasks file for acme certs
# all tasks are in a block just so we can set the ansible_connection to local
# some of the openssl modules require outputting to a file
# all files are deleted by the last task

# Generate new account key
- name: Generate new account key
  when: >
    certmgmt_acme_account_key is not defined or
    not certmgmt_acme_account_key
  block:
    - name: Generate account key
      community.crypto.openssl_privatekey_pipe:
      register: certmgmt_account_key_new

    - name: Set fact for account key
      ansible.builtin.set_fact:
        certmgmt_acme_account_key: '{{ certmgmt_account_key_new.privatekey }}'
