---
# tasks file for acme certs
# all tasks are in a block just so we can set the ansible_connection to local
# some of the openssl modules require outputting to a file
# all files are deleted by the last task

- name: 'Generate private key'
  community.crypto.openssl_privatekey_pipe:
    cipher: auto
  register: certmgmt_private_key

- name: Load cert info into variables
  ansible.builtin.set_fact:
    certmgmt_provision_return_object: '{{ certmgmt_provision_return_object | default([]) + [ certmgmt_this_cert ] }}'
  vars:
    certmgmt_this_cert:
      certmgmt_private_key: '{{ certmgmt_private_key.privatekey }}'
